import '../styles/globals.css'
import type { AppProps } from 'next/app'
import Layout from '../components/Layout'
import Head from 'next/head'
import { wrapper } from '../store'
import { StoreContext } from 'redux-react-hook'
import { createContext } from 'react'


function MyApp({ Component, pageProps }: AppProps) {
  return(
    <div className="container">
      <Layout>
        <Head>
          <title>Челны хлеб</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Component {...pageProps} />
      </Layout>
    </div>
  )
}

export default wrapper.withRedux(MyApp)


